spring:
  application:
    name: studymate
  profiles:
    active: local
server:
  port: 8088
logging:
  level: 
    '[com.studymate]': DEBUG
    '[org.springframework.web]': INFO
---
spring:
  config:
    activate:
      on-profile: local

 